[package]
name = "desktop"
version = "0.1.0"
authors = ["colin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
minifb = "0.19.1"
nesemu = {path = ".."}
image = "0.23.12"
